[colors.cursor]
cursor = "#f3ebfc"
text = "CellBackground"

[colors.primary]
background = "#0c0e11"
foreground = "#f3ebfc"

[colors.search.focused_match]
background = "#0c0e11"
foreground = "#ffffff"

[colors.search.matches]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black = "#0c0e11"
white = "#f3ebfc"
red = "#b70bda"
blue = "#ce7cd5"
magenta = "#944aeb"
cyan = "#7031ae"
green = "#d1a62e"
yellow = "#be3f17"


[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Noto Sans Mono"

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 0.95

[window.padding]
x = 15
y = 10
