[colors.cursor]
cursor = "#f3ebfc"
text = "CellBackground"

[colors.primary]
background = "#020619"
foreground = "#f3ebfc"

[colors.search.focused_match]
background = "#020619"
foreground = "#ffffff"

[colors.search.matches]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black = "#020619"
white = "#f3ebfc"
red = "#bd0cd7"
blue = "#8080ff"
cyan = "#dd3c56"
magenta = "#ea9fab"
green = "#d67661"
yellow = "#d34e2d"


[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Noto Sans Mono"

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 0.95

[window.padding]
x = 15
y = 10
