# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export PS1="\[${BOLD}${C6}\]> \[${RESET}${C5}\]\w \[${BOLD}${C3}\]\$ \[${RESET}\]"

export CWP="$P/theachristodoulidou"
export CWW="$HOME/.config/vscode"

# Aliases
alias cwp="cd $CWP"
alias code="code --user-data-dir $CWW"
alias feh="feh -d"
alias b="$BROWSER"
alias ls="ls --color=auto --group-directories-first"
alias lsm="ls -alth"
alias sizes="du -h --max-depth=1 | sort -hr"
alias gotop="gotop -a -c solarized16-dark"
alias pv="protonvpn-cli"
alias pvc="protonvpn-cli c -f"
alias pvd="protonvpn-cli d"
alias hdd="cd $HDD"
alias brc="$EDITOR $BRC"
alias bu="cd $BACKUP"
alias cloud="cd $CLOUD"
alias docs="cd $DOCS"
alias dots="cd $DOTS"
alias dw="cd $DW"
alias m="cd $M"
alias p="cd $P"
alias pics="cd $PICS"
alias prof="$EDITOR $PROF"
alias sc="cd $SC"
alias scr="cd $SCR"
alias sshthc="ssh root@$THCSERVER"
alias thc="cd $THC"
alias thcd="cd $THCD"
alias thcdocs="cd $THCDOCS"
alias thcpics="cd $THCPICS"
alias usys="yes | yay"
alias vids="cd $VIDS"
alias usb="cd $USB"
alias c="git commit -m"
alias gpus="git push"
alias gpul="git pull"
alias gpub="git rev-parse --abbrev-ref HEAD | xargs git push --set-upstream origin"
alias playall="ls -v *.wav *.mp3 *.mp4 | xargs vlc"
alias glog="git log --graph --full-history --all --color --pretty=format:\"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s\""s
alias pgadmin="cd $HOME/docker/pgadmin4 && docker-compose up "
alias twmin="yarn tailwindcss -o build.css --minify"